name: Packt CICD Linter Demo 
 
on: [push] 
 
jobs: 
  super-lint: 
    name: Packt CICD Lint Job 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v3 
 
      - name: Lint Code Base 
        uses: github/super-linter@v4 
        env: 
          DEFAULT_BRANCH: main 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
